# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hactl < Formula
  desc "Command-line interface for Home Assistant — built for humans and LLM agents"
  homepage "https://github.com/kfriede/hactl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfriede/hactl/releases/download/v0.1.0/hactl_0.1.0_darwin_amd64.tar.gz"
      sha256 "87afe3f70e353c1b8ec6625bc44b3f4ea19e7ba388fdde95798cc75b7e87907b"

      define_method(:install) do
        bin.install "hactl"
        generate_completions_from_executable(bin/"hactl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfriede/hactl/releases/download/v0.1.0/hactl_0.1.0_darwin_arm64.tar.gz"
      sha256 "c14b3c886659539d7c2538cd0e78c1ed2aa8ad1ec5509dbe698deccf9ea1f694"

      define_method(:install) do
        bin.install "hactl"
        generate_completions_from_executable(bin/"hactl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/hactl/releases/download/v0.1.0/hactl_0.1.0_linux_amd64.tar.gz"
      sha256 "238c5cd1b5877e576c05ba7caa5cf406ea249e599fe81eb02ee719d2f8716322"
      define_method(:install) do
        bin.install "hactl"
        generate_completions_from_executable(bin/"hactl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/hactl/releases/download/v0.1.0/hactl_0.1.0_linux_arm64.tar.gz"
      sha256 "ed207e8a6508811d1194885951ef1e6bfcfb7b534c27707a31a0cd45589a9e8a"
      define_method(:install) do
        bin.install "hactl"
        generate_completions_from_executable(bin/"hactl", "completion")
      end
    end
  end

  test do
    system "#{bin}/hactl", "version"
  end
end
