# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nab < Formula
  desc "CLI for You Need A Budget (YNAB) — built for humans and LLM agents"
  homepage "https://github.com/kfriede/nab"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfriede/nab/releases/download/v0.2.2/nab_0.2.2_darwin_amd64.tar.gz"
      sha256 "d2af2c683c136edb744db8bfc32b8ee0961b166f5ed7f2cf0019e19ec2ae0036"

      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfriede/nab/releases/download/v0.2.2/nab_0.2.2_darwin_arm64.tar.gz"
      sha256 "ca35e283cb7217ac536fbda1e540ed47195592d7b386e3d4eaf95f0693008eef"

      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/nab/releases/download/v0.2.2/nab_0.2.2_linux_amd64.tar.gz"
      sha256 "54d938dbc0685434e1a14db69be474b41cb545a4cc17433502ddd0a2c5296e24"
      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/nab/releases/download/v0.2.2/nab_0.2.2_linux_arm64.tar.gz"
      sha256 "504ffebd4526055a7ef9fdd35719b76a0ef95489c7349e35c5afedd96f2b0c88"
      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
  end

  test do
    system "#{bin}/nab", "version"
  end
end
