# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nab < Formula
  desc "CLI for You Need A Budget (YNAB) — built for humans and LLM agents"
  homepage "https://github.com/kfriede/nab"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfriede/nab/releases/download/v0.2.5/nab_0.2.5_darwin_amd64.tar.gz"
      sha256 "d2c82311933eb8995f2cea12669571ab602038c73ea95957684b775e1e291ea2"

      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfriede/nab/releases/download/v0.2.5/nab_0.2.5_darwin_arm64.tar.gz"
      sha256 "1ddd5345c44e7aa50e40e982f32171a59adca5bfc3ddf6043c3527ab9ca4842e"

      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/nab/releases/download/v0.2.5/nab_0.2.5_linux_amd64.tar.gz"
      sha256 "9bf87b224efc82de17cd1c623d6110e43cfc90dc5bf603a2c941a160ffe17281"
      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/nab/releases/download/v0.2.5/nab_0.2.5_linux_arm64.tar.gz"
      sha256 "fcab98c042438334b201b61f2473d550cf957a60a3472b87410566964f37860b"
      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
  end

  test do
    system "#{bin}/nab", "version"
  end
end
