# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nab < Formula
  desc "CLI for You Need A Budget (YNAB) — built for humans and LLM agents"
  homepage "https://github.com/kfriede/nab"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfriede/nab/releases/download/v0.2.0/nab_0.2.0_darwin_amd64.tar.gz"
      sha256 "07229630a7a5bd42a7e53fdcc8b628ba17774312381fc9eed9554883d46b1bf0"

      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfriede/nab/releases/download/v0.2.0/nab_0.2.0_darwin_arm64.tar.gz"
      sha256 "3181175087cab25ba5ff95fe43d20631513835ac5817ac9276340e44345affb3"

      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/nab/releases/download/v0.2.0/nab_0.2.0_linux_amd64.tar.gz"
      sha256 "d75ebc4b27258a5efba76abed88382314f1fe22d44972a3d0d883b9787775994"
      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/nab/releases/download/v0.2.0/nab_0.2.0_linux_arm64.tar.gz"
      sha256 "d0bf4ce2ad14a6f4b4fcfbcc312126557cfb534850aef4d311a358594605bdd9"
      define_method(:install) do
        bin.install "nab"
        generate_completions_from_executable(bin/"nab", "completion")
      end
    end
  end

  test do
    system "#{bin}/nab", "version"
  end
end
