# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uictl < Formula
  desc "CLI for managing UniFi network devices and controllers — built for humans and LLM agents"
  homepage "https://github.com/kfriede/uictl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfriede/uictl/releases/download/v0.1.0/uictl_0.1.0_darwin_amd64.tar.gz"
      sha256 "800fdb6317a7dcbd6fba2ffc44744e7c3c1cee15d4de97b3ffb06d3066429b64"

      define_method(:install) do
        bin.install "uictl"
        generate_completions_from_executable(bin/"uictl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfriede/uictl/releases/download/v0.1.0/uictl_0.1.0_darwin_arm64.tar.gz"
      sha256 "90684fef144fac3cb73d905d9b5d8de20977b4617a2b5cfc8746d0f931a322ed"

      define_method(:install) do
        bin.install "uictl"
        generate_completions_from_executable(bin/"uictl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/uictl/releases/download/v0.1.0/uictl_0.1.0_linux_amd64.tar.gz"
      sha256 "06436fddc820729b3ef295fdc3ed613945b3a866781f2a406371baba36ae1406"
      define_method(:install) do
        bin.install "uictl"
        generate_completions_from_executable(bin/"uictl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/uictl/releases/download/v0.1.0/uictl_0.1.0_linux_arm64.tar.gz"
      sha256 "06724eb62b421c16746bea890a53803533b781b405f11263b3b64eaec41feb96"
      define_method(:install) do
        bin.install "uictl"
        generate_completions_from_executable(bin/"uictl", "completion")
      end
    end
  end

  test do
    system "#{bin}/uictl", "version"
  end
end
