# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uictl < Formula
  desc "CLI for managing UniFi network devices and controllers — built for humans and LLM agents"
  homepage "https://github.com/kfriede/uictl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfriede/uictl/releases/download/v0.2.0/uictl_0.2.0_darwin_amd64.tar.gz"
      sha256 "09b42763f312b647e4865a3f76ea8fbacba68dfbb8ee4a326ec0b26540b471fa"

      define_method(:install) do
        bin.install "uictl"
        generate_completions_from_executable(bin/"uictl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfriede/uictl/releases/download/v0.2.0/uictl_0.2.0_darwin_arm64.tar.gz"
      sha256 "b868a8a98e04ebaa0f321a5301f4eb5a292bc314edcfa3337c355810195581fe"

      define_method(:install) do
        bin.install "uictl"
        generate_completions_from_executable(bin/"uictl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/uictl/releases/download/v0.2.0/uictl_0.2.0_linux_amd64.tar.gz"
      sha256 "6c837f6185af08c20ad5293bdfe2b84d89a7071bd5205651d1401e020603becd"
      define_method(:install) do
        bin.install "uictl"
        generate_completions_from_executable(bin/"uictl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfriede/uictl/releases/download/v0.2.0/uictl_0.2.0_linux_arm64.tar.gz"
      sha256 "9989fa737bb823f41ce00bb08a1144f101107484dbc99619c20cb5967942584f"
      define_method(:install) do
        bin.install "uictl"
        generate_completions_from_executable(bin/"uictl", "completion")
      end
    end
  end

  test do
    system "#{bin}/uictl", "version"
  end
end
